project_id = "jiyeljjdpyawaikgpkqu"

[functions.generate-pdf]
verify_jwt = false

[functions.batch-window-summary]
verify_jwt = false

[functions.list-jobs]
verify_jwt = false

[functions.fetch-quotes]
verify_jwt = false