project_id = "jiyeljjdpyawaikgpkqu"

[functions.save-quote]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.batch-window-summary]
verify_jwt = false

[functions.list-jobs]
verify_jwt = false

[functions.fetch-quotes]
verify_jwt = false

[functions.rooms-create]
verify_jwt = false

[functions.fetch-quote-details]
verify_jwt = false

[functions.jobber-oauth-start]
verify_jwt = false

[functions.jobber-oauth-callback]
verify_jwt = false

[functions.jobber-push-quote]
verify_jwt = false